;this file for FamiTone2 library generated by text2data tool

cave_music_data:
	.byte 4
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,307,256
	.word @song2ch0,@song2ch1,@song2ch2,@song2ch3,@song2ch4,307,256
	.word @song3ch0,@song3ch1,@song3ch2,@song3ch3,@song3ch4,307,256

@instruments:
	.byte $30 ;instrument $00
	.word @env1,@env0,@env0
	.byte $00
	.byte $30 ;instrument $04
	.word @env4,@env12,@env0
	.byte $00
	.byte $30 ;instrument $05
	.word @env8,@env0,@env0
	.byte $00
	.byte $30 ;instrument $08
	.word @env2,@env0,@env16
	.byte $00
	.byte $70 ;instrument $09
	.word @env3,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $0f
	.word @env5,@env0,@env0
	.byte $00
	.byte $30 ;instrument $10
	.word @env6,@env0,@env0
	.byte $00
	.byte $30 ;instrument $11
	.word @env11,@env15,@env0
	.byte $00
	.byte $30 ;instrument $12
	.word @env4,@env0,@env0
	.byte $00
	.byte $30 ;instrument $13
	.word @env9,@env0,@env0
	.byte $00
	.byte $30 ;instrument $15
	.word @env4,@env12,@env0
	.byte $00
	.byte $b0 ;instrument $16
	.word @env10,@env0,@env0
	.byte $00
	.byte $70 ;instrument $18
	.word @env7,@env13,@env0
	.byte $00
	.byte $30 ;instrument $19
	.word @env11,@env14,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $cc,$00,$00
@env2:
	.byte $c1,$c3,$c7,$c9,$00,$03
@env3:
	.byte $c9,$07,$c6,$05,$c9,$07,$c9,$00,$06
@env4:
	.byte $cf,$cd,$cb,$c9,$c7,$c5,$c3,$c1,$c0,$00,$08
@env5:
	.byte $cf,$cc,$c9,$c7,$c5,$c4,$c3,$c3,$c2,$03,$c8,$c6,$c4,$c3,$c3,$c2
	.byte $02,$c1,$03,$c4,$c3,$c2,$04,$c1,$04,$c3,$c2,$c1,$07,$c0,$00,$1d
@env6:
	.byte $c4,$c3,$c3,$c2,$03,$c1,$04,$c3,$c2,$c2,$c1,$08,$c2,$c2,$c1,$0a
	.byte $c2,$c1,$07,$c0,$00,$13
@env7:
	.byte $cf,$ce,$cd,$cc,$cb,$ca,$c9,$c1,$00,$07
@env8:
	.byte $cd,$cc,$ca,$c9,$c7,$c6,$c5,$c3,$c0,$00,$08
@env9:
	.byte $cb,$ca,$c8,$c7,$c5,$c4,$c3,$c1,$c0,$00,$08
@env10:
	.byte $c1,$c3,$c4,$c6,$c7,$c8,$c9,$ca,$ca,$cb,$cc,$cc,$cd,$0d,$cc,$cc
	.byte $cb,$ca,$c7,$c1,$00,$13
@env11:
	.byte $ce,$ce,$cd,$02,$cc,$04,$cb,$04,$ca,$03,$c9,$05,$c8,$06,$c7,$04
	.byte $c6,$06,$c5,$09,$c4,$08,$c3,$0c,$c2,$14,$c1,$1d,$c1,$00,$1c
@env12:
	.byte $c7,$c3,$c0,$bd,$00,$02
@env13:
	.byte $cc,$c0,$00,$01
@env14:
	.byte $c0,$03,$c3,$03,$c7,$03,$c3,$02,$c3,$00,$00
@env15:
	.byte $c0,$03,$c4,$03,$c7,$03,$c4,$02,$c4,$00,$00
@env16:
	.byte $c0,$0e,$bf,$be,$bd,$bc,$bd,$be,$bf,$c0,$00,$02


@song0ch0:
	.byte $fb,$06
@song0ch0loop:
@ref0:
	.byte $00,$ed,$8a,$5c,$8d
@ref1:
	.byte $6a,$a5,$67,$63,$60,$85,$5c,$bd,$5c,$85
@ref2:
	.byte $6a,$a5,$67,$63,$60,$85,$62,$b5,$6a,$8d
@ref3:
	.byte $62,$a5,$60,$85,$5c,$85,$60,$85,$5c,$ad,$6a,$8d
@ref4:
	.byte $5c,$ad,$74,$8d,$6a,$bd
@ref5:
	.byte $66,$ad,$6a,$85,$6c,$85,$62,$bd
@ref6:
	.byte $66,$ad,$6a,$85,$6c,$85,$6a,$bd
@ref7:
	.byte $66,$9d,$6c,$8d,$66,$8d,$6a,$85,$66,$85,$62,$85,$58,$85,$70,$85
	.byte $58,$85,$6c,$85,$70,$85
@ref8:
	.byte $6a,$ad,$6a,$8d,$74,$ad,$5c,$8d
	.byte $ff,$0a
	.word @ref1
	.byte $ff,$0a
	.word @ref2
	.byte $ff,$0c
	.word @ref3
	.byte $ff,$06
	.word @ref4
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref13:
	.byte $00,$f9,$83
@ref14:
	.byte $00,$85,$8c,$5c,$8d,$6a,$a5,$67,$63,$60,$85,$5c,$ad
@ref15:
	.byte $87,$5c,$85,$6a,$ad,$67,$63,$60,$85,$62,$ad
@ref16:
	.byte $87,$6a,$8d,$62,$a5,$60,$85,$5c,$85,$60,$85,$5c,$a5
@ref17:
	.byte $87,$6a,$8d,$5c,$ad,$74,$8d,$6a,$a5
@ref18:
	.byte $87,$6c,$b5,$58,$85,$6a,$85,$6c,$85,$62,$a5
@ref19:
	.byte $87,$6c,$b5,$62,$85,$6a,$85,$6c,$85,$6a,$a5
@ref20:
	.byte $8f,$5c,$85,$66,$9d,$6c,$8d,$66,$8d,$6a,$85,$66,$85,$62,$85,$5c
	.byte $85,$70,$85
@ref21:
	.byte $58,$85,$6c,$85,$70,$85,$6a,$ad,$6a,$8d,$74,$a5
@ref22:
	.byte $00,$85,$5c,$8d,$6a,$a5,$67,$63,$60,$85,$5c,$ad
	.byte $ff,$0b
	.word @ref15
	.byte $ff,$0d
	.word @ref16
	.byte $ff,$09
	.word @ref17
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref26:
	.byte $80,$14,$8d,$00,$85,$15,$01,$14,$8d,$00,$8d,$14,$8d,$00,$85,$15
	.byte $01,$14,$8d,$00,$8d
@ref27:
	.byte $14,$8d,$00,$85,$15,$01,$14,$8d,$00,$8d,$14,$8d,$00,$85,$15,$01
	.byte $14,$8d,$00,$8d
@ref28:
	.byte $14,$8d,$00,$85,$15,$01,$14,$8d,$00,$8d,$1a,$8d,$00,$85,$1b,$01
	.byte $1a,$8d,$00,$8d
@ref29:
	.byte $1a,$8d,$00,$85,$1b,$01,$1a,$8d,$00,$8d,$14,$8d,$00,$85,$15,$01
	.byte $14,$8d,$00,$8d
	.byte $ff,$14
	.word @ref27
@ref31:
	.byte $1e,$8d,$00,$85,$1f,$01,$1e,$8d,$00,$8d,$1a,$8d,$00,$85,$1b,$01
	.byte $1a,$8d,$00,$8d
	.byte $ff,$14
	.word @ref31
	.byte $ff,$14
	.word @ref31
	.byte $ff,$14
	.word @ref27
	.byte $ff,$14
	.word @ref27
	.byte $ff,$14
	.word @ref28
	.byte $ff,$14
	.word @ref29
	.byte $ff,$14
	.word @ref27
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref39:
	.byte $84,$20,$8d,$82,$20,$8d,$84,$20,$8d,$82,$20,$8d,$84,$20,$8d,$82
	.byte $20,$8d,$84,$20,$8d,$82,$20,$8d
	.byte $ff,$10
	.word @ref39
	.byte $ff,$10
	.word @ref39
	.byte $ff,$10
	.word @ref39
	.byte $ff,$10
	.word @ref39
	.byte $ff,$10
	.word @ref39
	.byte $ff,$10
	.word @ref39
	.byte $ff,$10
	.word @ref39
	.byte $ff,$10
	.word @ref39
	.byte $ff,$10
	.word @ref39
	.byte $ff,$10
	.word @ref39
	.byte $ff,$10
	.word @ref39
	.byte $ff,$10
	.word @ref39
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref52:
	.byte $f9,$85
@ref53:
	.byte $f9,$85
@ref54:
	.byte $f9,$85
@ref55:
	.byte $f9,$85
@ref56:
	.byte $f9,$85
@ref57:
	.byte $f9,$85
@ref58:
	.byte $f9,$85
@ref59:
	.byte $f9,$85
@ref60:
	.byte $f9,$85
@ref61:
	.byte $f9,$85
@ref62:
	.byte $f9,$85
@ref63:
	.byte $f9,$85
@ref64:
	.byte $f9,$85
	.byte $fd
	.word @song0ch4loop


@song1ch0:
	.byte $fb,$04
@song1ch0loop:
@ref65:
	.byte $00,$8d,$8c,$6c,$95,$68,$95,$5e,$95,$64,$95,$5e,$8d
@ref66:
	.byte $64,$8d,$5e,$95,$5a,$8d,$5a,$85,$5e,$85,$64,$8d,$5e,$85,$5a,$8d
	.byte $5e,$8d
@ref67:
	.byte $00,$8d,$6c,$95,$68,$95,$5e,$95,$64,$95,$5e,$8d
	.byte $ff,$12
	.word @ref66
@ref69:
	.byte $86,$3c,$bd,$3c,$8d,$3e,$85,$42,$8d,$46,$95
@ref70:
	.byte $3c,$bd,$3c,$8d,$3e,$85,$42,$8d,$46,$95
@ref71:
	.byte $3c,$95,$38,$95,$2e,$95,$34,$95,$2e,$8d,$34,$8d
@ref72:
	.byte $2e,$95,$2a,$95,$2a,$85,$2e,$85,$34,$8d,$2e,$85,$2a,$8d,$2e,$95
@ref73:
	.byte $00,$85,$8c,$6c,$c5,$68,$ad
@ref74:
	.byte $8f,$5e,$bd,$64,$85,$5e,$85,$5a,$85,$68,$85,$6c,$8d
@ref75:
	.byte $00,$85,$6c,$c5,$68,$ad
	.byte $ff,$0d
	.word @ref74
	.byte $fd
	.word @song1ch0loop

@song1ch1:
@song1ch1loop:
@ref77:
	.byte $8a,$6c,$95,$68,$95,$5e,$95,$64,$95,$5e,$8d,$64,$8d
@ref78:
	.byte $5e,$95,$5a,$95,$5a,$85,$5e,$85,$64,$8d,$5e,$85,$5a,$8d,$5e,$95
@ref79:
	.byte $6c,$95,$68,$95,$5e,$95,$64,$95,$5e,$8d,$64,$8d
	.byte $ff,$10
	.word @ref78
@ref81:
	.byte $88,$54,$bd,$54,$8d,$56,$85,$5a,$8d,$5e,$95
@ref82:
	.byte $54,$bd,$54,$8d,$56,$85,$5a,$8d,$5e,$95
@ref83:
	.byte $54,$95,$50,$95,$46,$95,$4c,$95,$46,$8d,$4c,$8d
@ref84:
	.byte $46,$95,$42,$95,$42,$85,$46,$85,$4c,$8d,$46,$85,$42,$8d,$46,$95
@ref85:
	.byte $8a,$6c,$bd,$68,$bd
@ref86:
	.byte $5e,$bd,$64,$8d,$5e,$85,$5a,$85,$68,$85,$6c,$95
@ref87:
	.byte $6c,$bd,$68,$bd
	.byte $ff,$0c
	.word @ref86
	.byte $fd
	.word @song1ch1loop

@song1ch2:
@song1ch2loop:
@ref89:
	.byte $80,$24,$bd,$20,$bd
@ref90:
	.byte $16,$bd,$1c,$bd
@ref91:
	.byte $24,$bd,$20,$bd
@ref92:
	.byte $16,$bd,$1c,$bd
@ref93:
	.byte $17,$17,$2f,$17,$17,$2f,$17,$2f,$1d,$1d,$35,$1d,$1d,$35,$1d,$35
	.byte $2b,$2b,$43,$2b,$2b,$43,$2b,$43,$2f,$2f,$47,$2f,$2f,$47,$2f,$46
	.byte $81
	.byte $ff,$21
	.word @ref93
	.byte $ff,$21
	.word @ref93
@ref96:
	.byte $16,$bd,$1c,$bd
@ref97:
	.byte $24,$bd,$20,$bd
@ref98:
	.byte $16,$bd,$1c,$bd
@ref99:
	.byte $24,$bd,$20,$bd
	.byte $ff,$21
	.word @ref93
	.byte $fd
	.word @song1ch2loop

@song1ch3:
@song1ch3loop:
@ref101:
	.byte $84,$20,$8d,$82,$20,$8d,$84,$20,$8d,$82,$20,$8d,$84,$20,$8d,$82
	.byte $20,$8d,$84,$20,$8d,$82,$20,$85,$84,$20,$85
@ref102:
	.byte $20,$8d,$82,$20,$8d,$84,$20,$8d,$82,$20,$8d,$84,$20,$8d,$82,$20
	.byte $8d,$84,$20,$8d,$82,$20,$85,$84,$20,$85
	.byte $ff,$12
	.word @ref102
	.byte $ff,$12
	.word @ref102
	.byte $ff,$12
	.word @ref102
	.byte $ff,$12
	.word @ref102
	.byte $ff,$12
	.word @ref102
	.byte $ff,$12
	.word @ref102
	.byte $ff,$12
	.word @ref102
	.byte $ff,$12
	.word @ref102
	.byte $ff,$12
	.word @ref102
	.byte $ff,$12
	.word @ref102
	.byte $fd
	.word @song1ch3loop

@song1ch4:
@song1ch4loop:
@ref113:
	.byte $f9,$85
@ref114:
	.byte $f9,$85
@ref115:
	.byte $f9,$85
@ref116:
	.byte $f9,$85
@ref117:
	.byte $f9,$85
@ref118:
	.byte $f9,$85
@ref119:
	.byte $f9,$85
@ref120:
	.byte $f9,$85
@ref121:
	.byte $f9,$85
@ref122:
	.byte $f9,$85
@ref123:
	.byte $f9,$85
@ref124:
	.byte $f9,$85
	.byte $fd
	.word @song1ch4loop


@song2ch0:
	.byte $fb,$06
@ref125:
	.byte $00,$f9,$83
@song2ch0loop:
@ref126:
	.byte $00,$f9,$83
@ref127:
	.byte $9a,$3a,$f9,$83
@ref128:
	.byte $3a,$f9,$83
@ref129:
	.byte $8e,$3c,$f9,$83
@ref130:
	.byte $9a,$3a,$f9,$83
@ref131:
	.byte $3a,$f9,$83
@ref132:
	.byte $3a,$f9,$83
@ref133:
	.byte $8e,$3c,$f9,$83
@ref134:
	.byte $9a,$3a,$f9,$83
@ref135:
	.byte $3a,$f9,$83
@ref136:
	.byte $3a,$f9,$83
@ref137:
	.byte $3a,$f9,$83
@ref138:
	.byte $3a,$f9,$83
@ref139:
	.byte $00,$f9,$83
	.byte $fd
	.word @song2ch0loop

@song2ch1:
@ref140:
	.byte $00,$f9,$83
@song2ch1loop:
@ref141:
	.byte $00,$f9,$83
@ref142:
	.byte $98,$3a,$b1,$45,$41,$3d,$3a,$bd
@ref143:
	.byte $3a,$b1,$45,$41,$3d,$3a,$bd
@ref144:
	.byte $3c,$ad,$44,$85,$45,$47,$44,$8d,$40,$8d,$3c,$8d,$36,$8d
@ref145:
	.byte $3a,$b1,$37,$33,$37,$3a,$9d,$22,$9d
@ref146:
	.byte $3a,$ad,$45,$45,$41,$3d,$3a,$bd
	.byte $ff,$08
	.word @ref146
	.byte $ff,$0e
	.word @ref144
	.byte $ff,$09
	.word @ref145
@ref150:
	.byte $96,$48,$8d,$00,$85,$49,$45,$48,$85,$4a,$85,$4e,$85,$40,$85,$52
	.byte $8d,$4e,$85,$4a,$95,$48,$85,$44,$85
@ref151:
	.byte $48,$8d,$00,$85,$49,$45,$48,$85,$44,$85,$40,$85,$3a,$85,$3e,$8d
	.byte $40,$85,$44,$8d,$48,$85,$4a,$8d
@ref152:
	.byte $48,$8d,$00,$85,$49,$45,$48,$85,$4a,$85,$4e,$85,$40,$85,$52,$8d
	.byte $4e,$85,$4a,$95,$48,$85,$44,$85
@ref153:
	.byte $48,$89,$00,$89,$49,$45,$48,$85,$44,$85,$40,$85,$3a,$85,$3e,$8d
	.byte $40,$85,$3e,$8d,$00,$85,$40,$85,$3e,$85
@ref154:
	.byte $3a,$8d,$00,$ed
	.byte $fd
	.word @song2ch1loop

@song2ch2:
@ref155:
	.byte $90,$22,$89,$23,$2c,$85,$24,$85,$22,$89,$23,$2c,$85,$29,$25,$22
	.byte $89,$23,$2c,$85,$24,$85,$22,$89,$23,$2c,$85,$29,$24,$81
@song2ch2loop:
	.byte $ff,$1d
	.word @ref155
@ref157:
	.byte $22,$89,$23,$2c,$85,$24,$85,$22,$89,$23,$2c,$85,$29,$25,$22,$89
	.byte $23,$2c,$85,$24,$85,$22,$89,$23,$2c,$85,$29,$24,$81
	.byte $ff,$1d
	.word @ref157
@ref159:
	.byte $24,$89,$25,$32,$85,$2c,$85,$24,$89,$25,$32,$85,$31,$2d,$24,$89
	.byte $25,$32,$85,$2c,$85,$24,$89,$25,$32,$85,$31,$2c,$81
	.byte $ff,$1d
	.word @ref157
	.byte $ff,$1d
	.word @ref157
	.byte $ff,$1d
	.word @ref157
	.byte $ff,$1d
	.word @ref159
	.byte $ff,$1d
	.word @ref157
	.byte $ff,$1d
	.word @ref157
	.byte $ff,$1d
	.word @ref157
	.byte $ff,$1d
	.word @ref157
	.byte $ff,$1d
	.word @ref157
	.byte $ff,$1d
	.word @ref157
	.byte $fd
	.word @song2ch2loop

@song2ch3:
@ref170:
	.byte $92,$20,$8d,$94,$20,$8d,$92,$21,$20,$85,$21,$94,$20,$85,$20,$85
	.byte $92,$20,$8d,$94,$20,$8d,$92,$21,$20,$85,$21,$94,$20,$85,$20,$85
@song2ch3loop:
	.byte $ff,$18
	.word @ref170
	.byte $ff,$18
	.word @ref170
	.byte $ff,$18
	.word @ref170
	.byte $ff,$18
	.word @ref170
	.byte $ff,$18
	.word @ref170
	.byte $ff,$18
	.word @ref170
	.byte $ff,$18
	.word @ref170
	.byte $ff,$18
	.word @ref170
	.byte $ff,$18
	.word @ref170
	.byte $ff,$18
	.word @ref170
	.byte $ff,$18
	.word @ref170
	.byte $ff,$18
	.word @ref170
	.byte $ff,$18
	.word @ref170
	.byte $ff,$18
	.word @ref170
	.byte $fd
	.word @song2ch3loop

@song2ch4:
@ref185:
	.byte $f9,$85
@song2ch4loop:
@ref186:
	.byte $f9,$85
@ref187:
	.byte $f9,$85
@ref188:
	.byte $f9,$85
@ref189:
	.byte $f9,$85
@ref190:
	.byte $f9,$85
@ref191:
	.byte $f9,$85
@ref192:
	.byte $f9,$85
@ref193:
	.byte $f9,$85
@ref194:
	.byte $f9,$85
@ref195:
	.byte $f9,$85
@ref196:
	.byte $f9,$85
@ref197:
	.byte $f9,$85
@ref198:
	.byte $f9,$85
@ref199:
	.byte $f9,$85
	.byte $fd
	.word @song2ch4loop


@song3ch0:
	.byte $fb,$06
@song3ch0loop:
@ref200:
	.byte $8a,$5d,$63,$5b,$63,$5d,$63,$5b,$63,$5d,$63,$5b,$63,$5d,$63,$5b
	.byte $62,$81
@ref201:
	.byte $5d,$63,$5b,$63,$5d,$63,$5b,$63,$5d,$63,$5b,$63,$5d,$63,$5b,$62
	.byte $81
@ref202:
	.byte $86,$2c,$9d,$2a,$9d
@ref203:
	.byte $28,$9d,$2a,$9d
@ref204:
	.byte $44,$9d,$48,$9d
@ref205:
	.byte $4a,$9d,$4e,$9d
	.byte $fd
	.word @song3ch0loop

@song3ch1:
@song3ch1loop:
@ref206:
	.byte $88,$5d,$63,$5b,$63,$5d,$63,$5b,$63,$5d,$63,$5b,$63,$5d,$63,$5b
	.byte $62,$81
	.byte $ff,$11
	.word @ref201
@ref208:
	.byte $44,$9d,$42,$9d
@ref209:
	.byte $40,$9d,$42,$9d
@ref210:
	.byte $5c,$9d,$60,$9d
@ref211:
	.byte $62,$9d,$66,$9d
	.byte $fd
	.word @song3ch1loop

@song3ch2:
@song3ch2loop:
@ref212:
	.byte $80,$15,$1b,$1b,$15,$1b,$1b,$15,$1b,$15,$1b,$1b,$15,$1b,$1b,$15
	.byte $1a,$81
@ref213:
	.byte $13,$1b,$1b,$13,$1b,$1b,$13,$1b,$13,$1b,$1b,$13,$1b,$1b,$13,$1a
	.byte $81
@ref214:
	.byte $2d,$33,$2d,$33,$2d,$33,$2d,$33,$2b,$33,$2b,$33,$2b,$33,$2b,$32
	.byte $81
@ref215:
	.byte $29,$33,$29,$33,$29,$33,$29,$33,$2b,$33,$2b,$33,$2b,$33,$2b,$32
	.byte $81
	.byte $ff,$11
	.word @ref214
	.byte $ff,$11
	.word @ref215
	.byte $fd
	.word @song3ch2loop

@song3ch3:
@song3ch3loop:
@ref218:
	.byte $94,$20,$20,$21,$21,$20,$20,$21,$21,$21,$21,$20,$20,$21,$21,$20
	.byte $20,$21,$21,$21,$20,$81
@ref219:
	.byte $20,$20,$21,$21,$20,$20,$21,$21,$21,$21,$20,$20,$21,$21,$20,$20
	.byte $21,$21,$20,$20,$20,$20
@ref220:
	.byte $84,$21,$21,$82,$20,$89,$84,$21,$82,$20,$85,$84,$21,$21,$82,$20
	.byte $89,$84,$21,$82,$20,$85
	.byte $ff,$0e
	.word @ref220
	.byte $ff,$0e
	.word @ref220
	.byte $ff,$0e
	.word @ref220
	.byte $fd
	.word @song3ch3loop

@song3ch4:
@song3ch4loop:
@ref224:
	.byte $bf
@ref225:
	.byte $bf
@ref226:
	.byte $bf
@ref227:
	.byte $bf
@ref228:
	.byte $bf
@ref229:
	.byte $bf
	.byte $fd
	.word @song3ch4loop
