;this file for FamiTone2 library generated by text2data tool

test_music_data:
	.byte 2
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,307,256

@instruments:
	.byte $30 ;instrument $00
	.word @env2,@env0,@env0
	.byte $00
	.byte $30 ;instrument $01
	.word @env1,@env0,@env10
	.byte $00
	.byte $70 ;instrument $02
	.word @env3,@env0,@env0
	.byte $00
	.byte $30 ;instrument $03
	.word @env4,@env8,@env0
	.byte $00
	.byte $30 ;instrument $04
	.word @env5,@env9,@env0
	.byte $00
	.byte $30 ;instrument $05
	.word @env7,@env0,@env0
	.byte $00
	.byte $30 ;instrument $06
	.word @env6,@env0,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $c9,$00,$00
@env2:
	.byte $cf,$00,$00
@env3:
	.byte $c9,$07,$c6,$05,$c9,$07,$c9,$00,$06
@env4:
	.byte $c6,$00,$00
@env5:
	.byte $c9,$c7,$c5,$c4,$c2,$c0,$00,$05
@env6:
	.byte $c7,$c2,$c0,$00,$02
@env7:
	.byte $cd,$cb,$c9,$c8,$c6,$c4,$c2,$c1,$c0,$00,$08
@env8:
	.byte $cc,$c0,$00,$01
@env9:
	.byte $c7,$c3,$c0,$bd,$00,$02
@env10:
	.byte $c0,$0e,$bf,$be,$bd,$bc,$bd,$be,$bf,$c0,$00,$02


@song0ch0:
	.byte $fb,$04
@song0ch0loop:
@ref0:
	.byte $82,$40,$8d,$3a,$85,$32,$85,$42,$8d,$46,$85,$42,$85
@ref1:
	.byte $40,$8d,$3a,$85,$32,$85,$42,$8d,$46,$85,$42,$85
@ref2:
	.byte $4a,$8d,$40,$85,$3a,$85,$46,$85,$42,$85,$40,$85,$42,$85
	.byte $ff,$0e
	.word @ref2
@ref4:
	.byte $86,$59,$53,$4b,$53,$59,$53,$4b,$53,$59,$53,$4b,$53,$59,$53,$4b
	.byte $52,$81
@ref5:
	.byte $5b,$55,$4d,$55,$5b,$55,$4d,$55,$5b,$55,$4d,$55,$5b,$55,$4d,$54
	.byte $81
@ref6:
	.byte $62,$89,$5b,$59,$55,$52,$8d,$5a,$85,$58,$85,$5a,$85
@ref7:
	.byte $62,$89,$5b,$59,$5b,$55,$53,$5e,$85,$5a,$85,$58,$85,$5a,$85
@ref8:
	.byte $82,$32,$9d,$34,$9d
@ref9:
	.byte $32,$85,$40,$b5
@ref10:
	.byte $3a,$bd
@ref11:
	.byte $4a,$bd
@ref12:
	.byte $32,$bd
@ref13:
	.byte $87,$40,$85,$42,$85,$46,$85,$4a,$85,$46,$85,$42,$85,$3c,$85
@ref14:
	.byte $3a,$bd
@ref15:
	.byte $87,$36,$85,$3a,$85,$3c,$85,$40,$85,$42,$85,$40,$85,$3c,$85
@ref16:
	.byte $3a,$bd
	.byte $ff,$0f
	.word @ref15
@ref18:
	.byte $84,$40,$85,$41,$41,$3a,$85,$00,$8d,$42,$85,$46,$85,$43,$00,$81
@ref19:
	.byte $40,$85,$41,$41,$3a,$85,$00,$8d,$42,$85,$46,$85,$42,$85
@ref20:
	.byte $40,$85,$41,$41,$3a,$85,$00,$8d,$42,$85,$46,$85,$43,$00,$81
	.byte $ff,$0e
	.word @ref19
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref22:
	.byte $00,$83,$82,$40,$8d,$3a,$85,$32,$85,$42,$8d,$46,$85,$42
@ref23:
	.byte $85,$40,$8d,$3a,$85,$32,$85,$42,$8d,$46,$85,$42
@ref24:
	.byte $85,$4a,$8d,$40,$85,$3a,$85,$46,$85,$42,$85,$40,$85,$42
	.byte $ff,$0e
	.word @ref24
@ref26:
	.byte $84,$40,$95,$40,$85,$42,$95,$42,$85
@ref27:
	.byte $40,$85,$3c,$8d,$3c,$85,$34,$85,$3c,$85,$4c,$8d
@ref28:
	.byte $4a,$9d,$4c,$9d
@ref29:
	.byte $4a,$9d,$46,$9d
@ref30:
	.byte $01,$32,$9d,$34,$99
@ref31:
	.byte $8b,$41,$42,$85,$46,$85,$4a,$85,$46,$85,$42,$85,$3c,$85
@ref32:
	.byte $83,$3a,$b9
	.byte $ff,$0f
	.word @ref15
@ref34:
	.byte $4b,$4b,$4f,$4b,$4b,$4f,$53,$55,$52,$8d,$4e,$85,$4a,$85
@ref35:
	.byte $87,$4a,$85,$52,$85,$58,$85,$4c,$85,$4c,$85,$54,$85,$5a,$85
@ref36:
	.byte $80,$3a,$95,$40,$8d,$34,$8d,$32,$85
@ref37:
	.byte $87,$42,$b5
@ref38:
	.byte $3a,$95,$40,$8d,$34,$8d,$32,$85
@ref39:
	.byte $87,$42,$b5
@ref40:
	.byte $86,$59,$4b,$53,$55,$59,$4b,$53,$55,$59,$4b,$53,$55,$59,$4b,$53
	.byte $54,$81
@ref41:
	.byte $59,$4b,$53,$55,$59,$4b,$53,$55,$59,$4b,$53,$55,$59,$4b,$53,$54
	.byte $81
@ref42:
	.byte $5b,$4d,$55,$59,$5b,$4d,$55,$59,$5b,$4d,$55,$59,$5b,$4d,$55,$58
	.byte $81
@ref43:
	.byte $82,$46,$a7,$84,$42,$85,$46,$85,$42,$83
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref44:
	.byte $80,$32,$85,$32,$85,$3a,$85,$40,$85,$34,$85,$34,$85,$3c,$85,$42
	.byte $85
@ref45:
	.byte $32,$85,$32,$85,$3a,$85,$40,$85,$34,$85,$34,$85,$3c,$85,$42,$85
	.byte $ff,$10
	.word @ref45
	.byte $ff,$10
	.word @ref45
@ref48:
	.byte $1b,$32,$32,$33,$1b,$32,$32,$33,$1b,$32,$32,$25,$3c,$3c,$3d,$25
	.byte $3c,$3c,$3d,$25,$3c,$3c
@ref49:
	.byte $23,$3a,$3a,$3b,$23,$3a,$3a,$3b,$23,$3a,$3a,$1d,$1d,$35,$1d,$1d
	.byte $35,$21,$38,$81
	.byte $ff,$16
	.word @ref48
	.byte $ff,$14
	.word @ref49
@ref52:
	.byte $32,$85,$32,$85,$34,$85,$32,$85,$34,$85,$3a,$85,$34,$85,$32,$85
@ref53:
	.byte $32,$85,$32,$85,$34,$85,$32,$85,$34,$85,$3a,$85,$32,$85,$34,$85
@ref54:
	.byte $32,$8d,$34,$85,$32,$85,$34,$85,$3a,$85,$34,$85,$32,$83,$32
@ref55:
	.byte $22,$85,$3a,$3a,$3b,$22,$85,$3b,$3a,$3a,$1c,$85,$34,$34,$35,$1c
	.byte $85,$35,$34,$34
	.byte $ff,$10
	.word @ref52
	.byte $ff,$10
	.word @ref53
	.byte $ff,$0f
	.word @ref54
	.byte $ff,$14
	.word @ref55
@ref60:
	.byte $32,$8d,$34,$85,$32,$85,$34,$85,$3a,$85,$34,$85,$23,$22,$22
@ref61:
	.byte $3a,$85,$52,$52,$53,$3a,$85,$53,$52,$52,$34,$85,$4c,$4c,$4d,$34
	.byte $85,$4d,$4c,$4c
@ref62:
	.byte $32,$85,$32,$85,$3a,$85,$3a,$85,$34,$85,$34,$85,$3c,$85,$34,$85
@ref63:
	.byte $32,$85,$32,$85,$3a,$85,$3a,$85,$34,$85,$34,$85,$3c,$85,$42,$85
	.byte $ff,$10
	.word @ref62
	.byte $ff,$10
	.word @ref63
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref66:
	.byte $8a,$21,$8c,$1b,$8a,$21,$21,$88,$21,$8c,$1b,$8a,$21,$8c,$1b,$8a
	.byte $21,$8c,$1b,$8a,$21,$21,$88,$21,$8c,$1b,$8a,$21,$8c,$1a,$81
@ref67:
	.byte $8a,$20,$8c,$1a,$1e,$1a,$8a,$21,$21,$88,$21,$8c,$1b,$8a,$21,$8c
	.byte $1b,$8a,$21,$8c,$1b,$8a,$21,$21,$88,$21,$8a,$21,$88,$21,$8a,$1a
	.byte $81
@ref68:
	.byte $21,$8c,$1b,$8a,$21,$8c,$1b,$88,$21,$8c,$1b,$8a,$20,$8c,$1a,$8a
	.byte $21,$8c,$1b,$8a,$21,$21,$8c,$1b,$88,$21,$8a,$21,$21,$8c,$1a,$81
@ref69:
	.byte $8a,$21,$8c,$1b,$8a,$21,$8c,$1b,$88,$21,$8c,$1b,$88,$21,$1f,$21
	.byte $21,$1f,$1f,$03,$03,$21,$20,$81
	.byte $ff,$11
	.word @ref66
	.byte $ff,$13
	.word @ref67
	.byte $ff,$12
	.word @ref68
	.byte $ff,$11
	.word @ref69
@ref74:
	.byte $8a,$21,$8c,$1b,$1f,$1b,$8a,$21,$8c,$1b,$1f,$1b,$8a,$21,$8c,$1b
	.byte $1f,$1b,$8a,$21,$8c,$1b,$8a,$21,$20,$81
@ref75:
	.byte $21,$1b,$8c,$1b,$1f,$8a,$21,$8c,$1a,$1e,$1a,$1e,$1b,$8a,$21,$8c
	.byte $1b,$1f,$1b,$8a,$21,$8c,$1b,$8a,$21,$20,$81
@ref76:
	.byte $21,$8c,$1b,$1f,$1b,$8a,$21,$8c,$1b,$1f,$1b,$8a,$21,$8c,$1b,$1f
	.byte $1b,$8a,$21,$8c,$1b,$8a,$21,$20,$81
	.byte $ff,$13
	.word @ref75
	.byte $ff,$11
	.word @ref76
	.byte $ff,$13
	.word @ref75
	.byte $ff,$11
	.word @ref76
	.byte $ff,$13
	.word @ref75
	.byte $ff,$11
	.word @ref76
	.byte $ff,$13
	.word @ref75
@ref84:
	.byte $21,$8c,$1b,$8a,$21,$8c,$1b,$88,$21,$8c,$1b,$8a,$20,$8c,$1a,$8a
	.byte $21,$8c,$1b,$8a,$21,$21,$8c,$1b,$88,$21,$8c,$1b,$1f,$1a,$81
@ref85:
	.byte $8a,$21,$8c,$1b,$8a,$21,$8c,$1b,$88,$21,$8c,$1a,$1e,$8a,$20,$8c
	.byte $1a,$1e,$1a,$1f,$8a,$1b,$21,$8c,$1b,$88,$21,$8a,$21,$88,$21,$8a
	.byte $20,$81
	.byte $ff,$12
	.word @ref68
	.byte $ff,$11
	.word @ref69
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref88:
	.byte $bf
@ref89:
	.byte $bf
@ref90:
	.byte $bf
@ref91:
	.byte $bf
@ref92:
	.byte $bf
@ref93:
	.byte $bf
@ref94:
	.byte $bf
@ref95:
	.byte $bf
@ref96:
	.byte $bf
@ref97:
	.byte $bf
@ref98:
	.byte $bf
@ref99:
	.byte $bf
@ref100:
	.byte $bf
@ref101:
	.byte $bf
@ref102:
	.byte $bf
@ref103:
	.byte $bf
@ref104:
	.byte $bf
@ref105:
	.byte $bf
@ref106:
	.byte $bf
@ref107:
	.byte $bf
@ref108:
	.byte $bf
@ref109:
	.byte $bf
	.byte $fd
	.word @song0ch4loop


@song1ch0:
	.byte $fb,$06
@song1ch0loop:
@ref110:
	.byte $00
	.byte $fd
	.word @song1ch0loop

@song1ch1:
@song1ch1loop:
@ref111:
	.byte $00
	.byte $fd
	.word @song1ch1loop

@song1ch2:
@song1ch2loop:
@ref112:
	.byte $00
	.byte $fd
	.word @song1ch2loop

@song1ch3:
@song1ch3loop:
@ref113:
	.byte $00
	.byte $fd
	.word @song1ch3loop

@song1ch4:
@song1ch4loop:
@ref114:
	.byte $81
	.byte $fd
	.word @song1ch4loop
