// ..\dev\assets\enems0.h
// Generated by eneexp3c.exe v0.1 [20170405]
// Copyleft 2016 The Mojon Twins

// Enems structure is {T YX1 YX2 P} x 3 x MAP_W x MAP_H
// y coordinates are adjusted by 1 positions

const unsigned char enems_0_00 [] = {
	0x10, 0x9a, 0x97, 0x01, 0
};

const unsigned char enems_0_01 [] = {
	0x23, 0xbd, 0x6d, 0x01, 0
};

const unsigned char enems_0_02 [] = {
	0x23, 0xaa, 0xa5, 0x01, 0
};

const unsigned char enems_0_03 [] = {
	0xb0, 0xce, 0xc6, 0x00, 0
};

const unsigned char enems_0_04 [] = {
	0x11, 0x87, 0xb9, 0x01, 0
};

const unsigned char enems_0_05 [] = {
	0x11, 0x5a, 0xbb, 0x02, 0
};

const unsigned char enems_0_06 [] = {
	0x12, 0x82, 0x88, 0x01, 0
};

const unsigned char enems_0_08 [] = {
	0x33, 0x4a, 0x49, 0x00, 0x23, 0xa8, 0xa2, 0x01, 0
};

const unsigned char enems_0_09 [] = {
	0x11, 0x44, 0xa6, 0x02, 0x33, 0x8d, 0x8c, 0x00, 0
};

const unsigned char * const enems_0 [] = {
	enems_0_00, enems_0_01, enems_0_02, enems_0_03, enems_0_04, enems_0_05, enems_0_06, 0, 
	enems_0_08, enems_0_09
};

// Bytes: 73 vs. MAP_WxMAP_Hx12 = 120 (60%)

#define MAX_ENEMS_0_TYPE_10	5
#define MAX_ENEMS_0_TYPE_20	3
#define MAX_ENEMS_0_TYPE_30	2
#define MAX_ENEMS_0_TYPE_B0	1

